CREATE SEQUENCE SEQ_SB_ID;

CREATE TABLE SERVICE_BULLETIN
(
  SB_ID BIGINT DEFAULT nextval('SEQ_SB_ID') UNIQUE NOT NULL,
  SB_NUMBER VARCHAR(255) NOT NULL,
  SB_VERSION BIGINT NOT NULL,
  TITLE VARCHAR(4000) NOT NULL,
  DESCRIPTION VARCHAR(4000),
  ENGINE_MODEL VARCHAR(255) NOT NULL,
  COMPLIANCE_CATEGORY BIGINT,
  IMPACT_CATEGORY VARCHAR(255),
  ESN_APPLICABILITY JSON,
  STATUS VARCHAR(255) DEFAULT 'UNACCEPTED' NOT NULL,
  ACTIVE BOOLEAN DEFAULT TRUE,
  CREATED_BY VARCHAR(255),
  CREATED_DATE TIMESTAMP DEFAULT NOW(),
  LAST_MODIFIED_BY VARCHAR(255),
  LAST_MODIFIED_DATE TIMESTAMP DEFAULT NOW()
 );

ALTER TABLE SERVICE_BULLETIN ADD CONSTRAINT SB_PRIMARY_KEY PRIMARY KEY (SB_NUMBER, SB_VERSION);
