/* Replace with your SQL commands */
CREATE SEQUENCE SEQ_MODULE_HIERARCHY_ID;

CREATE TABLE ENGINE_MODULE_HIERARCHY
(
  ID BIGINT PRIMARY KEY DEFAULT nextval('SEQ_MODULE_HIERARCHY_ID'),
  ENGINE_FAMILY VARCHAR(255) NOT NULL,
  VERSION INTEGER DEFAULT 1 NOT NULL,
  MODULE_ID INTEGER NOT NULL,
  MODULE_NUMBER VARCHAR(64),
  MODULE_NAME VARCHAR(255) NOT NULL,
  ATA VARCHAR(255),
  PART_NUMBER_PATTERN VARCHAR(64),
  PARENT_MODULE_ID INTEGER DEFAULT 0 NOT NULL,
  CREATED_BY VARCHAR(255),
  CREATED_DATE TIMESTAMP DEFAULT NOW(),
  LAST_MODIFIED_BY VARCHAR(255),
  LAST_MODIFIED_DATE TIMESTAMP DEFAULT NOW()
 );

ALTER TABLE ENGINE_MODULE_HIERARCHY ADD CONSTRAINT MODULE_HIERARCHY_UNIQUE_KEY UNIQUE (ENGINE_FAMILY, MODULE_ID, VERSION);