CREATE SEQUENCE SEQ_SB_ATA_ID;

CREATE TABLE SERVICE_BULLETIN_ATA
(
  ID BIGINT DEFAULT nextval('SEQ_SB_ATA_ID') PRIMARY KEY NOT NULL,
  SB_ID BIGINT NOT NULL,
  SB_NUMBER VARCHAR(255) NOT NULL,
  SB_VERSION BIGINT NOT NULL,
  ATA VARCHAR(255),
  CREATED_BY VARCHAR(255),
  CREATED_DATE TIMESTAMP DEFAULT NOW(),
  LAST_MODIFIED_BY VARCHAR(255),
  LAST_MODIFIED_DATE TIMESTAMP DEFAULT NOW()
 );

ALTER TABLE SERVICE_BULLETIN_ATA ADD FOREIGN KEY (SB_ID) REFERENCES SERVICE_BULLETIN (SB_ID);
