/* Replace with your SQL commands */
CREATE SEQUENCE SEQ_EM_AUDIT_ID;

CREATE TABLE ENGINE_MODULE_HIERARCHY_AUDIT
(
  ID BIGINT DEFAULT nextval('SEQ_EM_AUDIT_ID') PRIMARY KEY NOT NULL,
  ENGINE_FAMILY VARCHAR(255) NOT NULL,
  MODULE_ID INTEGER NOT NULL,
  VERSION INTEGER NOT NULL,
  USER_ACTION VARCHAR(255),
  ENGINE_MODULE_DATA JSON,
  MODIFIED_BY VARCHAR(255),
  MODIFIED_DATE TIMESTAMP
 );

ALTER TABLE ENGINE_MODULE_HIERARCHY_AUDIT 
ADD FOREIGN KEY (ENGINE_FAMILY, MODULE_ID, VERSION) REFERENCES ENGINE_MODULE_HIERARCHY (ENGINE_FAMILY, MODULE_ID, VERSION);
